# Generated by Django 4.0 on 2022-01-04 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmdetails', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='stockquantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='items',
            name='volume',
            field=models.IntegerField(null=True),
        ),
    ]
