# Generated by Django 4.0 on 2022-01-04 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmdetails', '0002_items_stockquantity_items_volume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='costperitem',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='stockquantity',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='volume',
            field=models.BigIntegerField(null=True),
        ),
    ]
